pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
        jdk 'JDK'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Build') {
            steps {
                echo 'This is a minimal pipeline.'
                sh 'mvn clean install'
                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
                currentBuild.description = "Release: ${env.version}"
            }
        }
        stage('Image') {
            echo "Docker Image Tag Name: ${env.version}"
            sh "docker stop forecast"
            sh "docker rm forecast"
            sh "docker run --name forecast -d -p 3000:3000 forecast:${env.version}"
        }
    }
}